"""add_reset_password_tokens_and_file_size

Revision ID: 26932420b887
Revises: 9a15f70d18d7
Create Date: 2026-03-18 18:52:38.272423
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26932420b887'
down_revision: Union[str, None] = '9a15f70d18d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_materials', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reset_password_token', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('reset_password_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_expires')
    op.drop_column('users', 'reset_password_token')
    op.drop_column('user_materials', 'file_size')
    # ### end Alembic commands ###
