"""Initial migration

Revision ID: 9a15f70d18d7
Revises: 
Create Date: 2026-03-18 12:23:02.328485
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a15f70d18d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_boards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('board_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('session_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('concept_hash', sa.String(length=64), nullable=False),
    sa.Column('concept_name', sa.String(length=500), nullable=False),
    sa.Column('study_level', sa.String(length=50), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('segments_data', sa.JSON(), nullable=False),
    sa.Column('animations_data', sa.JSON(), nullable=True),
    sa.Column('whiteboard_data', sa.JSON(), nullable=True),
    sa.Column('script_content', sa.Text(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_cache_concept_hash'), 'session_cache', ['concept_hash'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('SCHOOL_STUDENT', 'COLLEGE_STUDENT', 'WORKING_PROFESSIONAL', 'SELF_LEARNER', 'COMPETITIVE_EXAM', name='user_type_enum'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('board', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_code', sa.String(length=10), nullable=True),
    sa.Column('verification_code_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('voice_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('elevenlabs_voice_id', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('accent', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('tutor_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['curriculum_boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_playlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('concept_name', sa.String(length=500), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_chapters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['curriculum_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('topic_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_concepts', sa.JSON(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['curriculum_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_banks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['curriculum_topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('playlist_id', sa.Uuid(), nullable=True),
    sa.Column('playlist_order', sa.Integer(), nullable=True),
    sa.Column('concept_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mood', sa.Enum('VERY_FOCUSED', 'FOCUSED', 'LIGHT', 'NON_ATTENTIVE', 'TIRED', 'CURIOUS', 'EXAM_PREP', name='user_mood_enum'), nullable=False),
    sa.Column('model_personality', sa.Enum('STRICT', 'VERY_FRIENDLY', 'ATTENTIVE', 'FUNNY', 'MOTIVATIONAL', 'PATIENT', 'STORYTELLER', name='model_personality_enum'), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('duration_type', sa.Enum('USER_DEFINED', 'AI_DETERMINED', name='duration_type_enum'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('voice_id', sa.Uuid(), nullable=True),
    sa.Column('session_mode', sa.Enum('SINGLE_SESSION', 'MULTIPLE_SESSIONS', name='session_mode_enum'), nullable=False),
    sa.Column('study_level', sa.Enum('BEGINNER', 'BASIC', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='study_level_enum'), nullable=False),
    sa.Column('entire_session_type', sa.Enum('BASIC_OVERVIEW', 'INTERMEDIATE', 'IN_DEPTH', 'EXAM_FOCUSED', 'REVISION', name='entire_session_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PREPARING', 'READY', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'CANCELLED', name='session_status_enum'), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('chapter_id', sa.Uuid(), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('course', sa.String(length=255), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('professional_background', sa.String(length=255), nullable=True),
    sa.Column('user_profession', sa.String(length=50), nullable=True),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('system_prompt_snapshot', sa.Text(), nullable=True),
    sa.Column('session_evaluation', sa.JSON(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('pulse_average', sa.Float(), nullable=True),
    sa.Column('pulse_percentage', sa.Float(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['curriculum_boards.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['curriculum_chapters.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['session_playlists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['curriculum_subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['curriculum_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_id'], ['voice_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_sessions_user_id'), 'tutor_sessions', ['user_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('interaction_type', sa.Enum('DOUBT', 'PULSE_CHECK', 'MCQ', 'CHAT', 'HAND_RAISE', 'SEGMENT_TRANSITION', 'CONFIG_CHANGE', 'CELEBRATION', 'CURIOSITY_TRIGGER', 'STORY', name='interaction_type_enum'), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp_in_session_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pulse_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp_in_session_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('personality', sa.String(length=50), nullable=False),
    sa.Column('study_level', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('session_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('formulas', sa.JSON(), nullable=True),
    sa.Column('diagrams', sa.JSON(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('session_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.Enum('INTRODUCTION', 'CORE_TEACHING', 'EXAMPLE', 'ANALOGY', 'WHITEBOARD', 'ANIMATION_DEMO', 'PRACTICE', 'QA_CHECK', 'STORY', 'CURIOSITY_TRIGGER', 'RECAP', 'SUMMARY', name='segment_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_script', sa.Text(), nullable=True),
    sa.Column('teaching_notes', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='segment_status_enum'), nullable=False),
    sa.Column('animation_cues', sa.JSON(), nullable=True),
    sa.Column('whiteboard_cues', sa.JSON(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'IMAGE', 'TEXT', 'DOCUMENT', 'QUESTION_BANK', name='material_type_enum'), nullable=False),
    sa.Column('extracted_content', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animation_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=True),
    sa.Column('animation_type', sa.Enum('DIAGRAM', 'FLOWCHART', 'NETWORK_GRAPH', 'TIMELINE', 'PROCESS_ANIMATION', 'COMPARISON', 'HIERARCHY', 'REAL_WORLD_ANALOGY', 'CODE_WALKTHROUGH', 'MATH_VISUALIZATION', 'CUSTOM', name='animation_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('animation_spec', sa.JSON(), nullable=False),
    sa.Column('trigger_timestamp_seconds', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sync_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['session_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doubt_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=True),
    sa.Column('doubt_text', sa.Text(), nullable=True),
    sa.Column('doubt_image_path', sa.String(length=500), nullable=True),
    sa.Column('ocr_extracted_text', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_method', sa.String(length=50), nullable=True),
    sa.Column('timestamp_in_session_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['session_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcq_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.String(length=500), nullable=False),
    sa.Column('user_answer', sa.String(length=500), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['session_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whiteboard_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('whiteboard_spec', sa.JSON(), nullable=False),
    sa.Column('trigger_timestamp_seconds', sa.Integer(), nullable=True),
    sa.Column('sync_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['session_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whiteboard_data')
    op.drop_table('mcq_questions')
    op.drop_table('doubt_records')
    op.drop_table('animation_data')
    op.drop_table('user_materials')
    op.drop_table('session_segments')
    op.drop_table('session_notes')
    op.drop_table('session_configs')
    op.drop_table('pulse_metrics')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_tutor_sessions_user_id'), table_name='tutor_sessions')
    op.drop_table('tutor_sessions')
    op.drop_table('question_banks')
    op.drop_table('curriculum_topics')
    op.drop_table('curriculum_chapters')
    op.drop_table('session_playlists')
    op.drop_table('curriculum_subjects')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_session_cache_concept_hash'), table_name='session_cache')
    op.drop_table('session_cache')
    op.drop_table('curriculum_boards')
    # ### end Alembic commands ###
