"""add_visuals_ready_to_session_segments

Revision ID: 9dbef749fbd1
Revises: 26932420b887
Create Date: 2026-04-01 15:52:57.926769
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dbef749fbd1'
down_revision: Union[str, None] = '26932420b887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_segments', sa.Column('visuals_ready', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_segments', 'visuals_ready')
    # ### end Alembic commands ###
